# Generated by Django 2.1.1 on 2018-09-17 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Content of the comment')),
                ('datetime', models.DateTimeField(auto_now=True, help_text='Date and time of the posting of the comment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='author',
        ),
        migrations.RenameModel(
            old_name='BlogModel',
            new_name='Blog',
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
        migrations.AddField(
            model_name='comment',
            name='origin_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
    ]
